# Site settings
title: Tyler Fisher
email: tyler@tylerjfisher.com
description: > # this means to ignore newlines until "baseurl:"
  News developer
baseurl: ""
url: "http://tylerjfisher.com"
twitter_username: tylrfishr
github_username:  TylerFisher

# Build settings
markdown: kramdown
